services:
  cv_redacted:
    build:
      context: .
      dockerfile: DOCKERFILE
    volumes:
      - ./dockervolume:/usr/src/app/Build
    command: python ./src/main.py
  cv:
    build:
      context: .
      dockerfile: DOCKERFILE
    environment:
      - SOPS_AGE_KEY=${SOPS_AGE_KEY}
      - AGE_RECIPIENT=${AGE_RECIPIENT}
    volumes:
      - ./dockervolume:/usr/src/app/Build
    command: bash -c "python ./src/main.py && ./encrypt_build.sh"
