name: Make Release
on:
  workflow_run:
    workflows: ["Compile Full Version", "Compile Public Version"]
    types:
      - completed
jobs:
  create_release:
    name: Create Release
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      - name: Download Redacted CV
        uses: actions/download-artifact@master
        with:
          name: Redacted CV
          path: ${{GITHUB_WORKSPACE}}/Artifacts
      - name: Download Full CV
        uses: actions/download-artifact@master
        with:
          name: Full CV
          path: ${{GITHUB_WORKSPACE}}/Artifacts
      - name: Get Date for Release Tag
        id: date_maker
        run: echo "::set-output name=date::$(date +'%Y%m%d')"
      - name: Release
        uses: softprops/action-gh-release@v2
        with:
          tag_name: CV-${{ steps.date.outputs.date }}
          name: CV Build from ${{ steps.date.outputs.date }}
          files: ${{GITHUB_WORKSPACE}}/Artifacts/*
          fail_on_unmatched_files: true
          make_latest: true
