name: Compile Public Version
on:
  push:
    branches:
      - main
      - feat/*
jobs:
  compile_pdf:
    runs-on: ubuntu-latest
    steps:
      - name: Compile
        uses: ./.github/actions/compile_pdf.yml
        with:
          artifact-name: "Redacted CV"
