name: Test
on:
  push:
    branches:
      - main
      - feat/*
jobs:
  compile_pdf:
    timeout-minutes: 10
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v1
      - name: Compile PDF in Container
        run: docker-compose -f "docker-compose.yml" up
      - name: Upload PDF as artifact
        uses: actions/upload-artifact@v4
        with:
          name: CV
          path: ./dockervolume/*.pdf
