name: Compile Public Version
on:
  push:
    branches:
      - main
      - feat/*
jobs:
  make_redacted_pdf:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v1
      - name: Compile
        uses: ./.github/workflows/compile_pdf.yml
        with:
          artifact-name: "Redacted CV"
